### ISSUE TITLE
Programming Basics with Python--KCL

### ISSUE THREAD

**Issue by mrmyothet** [mrmyothet/ipnd#11]
- [x] Chapter 1 :: Programming
- [x] Chapter 2 :: Programming
- [x] Chapter 3 :: Object Oriented
- [x] Chapter 4 :: Beginning Data Structure
- [x] Chapter 5 :: Queue
- [x] Chapter 6 :: List & Dictionary
- [x] Chapter 7 :: Recursion
- [x] Chapter 8 :: Searching & Sorting
- [x] Chapter 9 :: Tree
- [x] Chapter 10:: Algorithm Analysis

**Comment by Khun-Cho-Lwin** [comment]
I've finished all of the Chapter but I can't solve some of the quiz. So, I have to do some quiz.

**Comment by mrmyothet** [comment]
In order to distinguish with others.  
Please, create a folder `Programming Basics with Python--KCL` and move your chapters folders to it.  
Then, create a `pull request` to merge your changes into `master` branch.

**Comment by Khun-Cho-Lwin** [comment]
Do you mean own repository?

**Comment by mrmyothet** [comment]
**No.** 

After merge with master, to get the separate folders for each developer in our repository.  

![image](https://user-images.githubusercontent.com/16772482/90764788-e76dc700-e30e-11ea-83be-d250d4deae0d.png)

![image](https://user-images.githubusercontent.com/16772482/90765083-58ad7a00-e30f-11ea-9ea4-2d968e684a30.png)

**Comment by Khun-Cho-Lwin** [comment]
Ok bro, got it.
