### ISSUE TITLE
Programming Basics with Python--NDWH

### ISSUE THREAD

**Issue by mrmyothet** [mrmyothet/ipnd#14]
- [x] Chapter 1 :: Programming
- [x] Chapter 2 :: Programming
- [x] Chapter 3 :: Object Oriented
- [x] Chapter 4 :: Beginning Data Structure
- [x] Chapter 5 :: Queue
- [x] Chapter 6 :: List & Dictionary
- [x] Chapter 7 :: Recursion
- [x] Chapter 8 :: Searching & Sorting
- [x] Chapter 9 :: Tree
- [x] Chapter 10:: Algorithm Analysis

**Comment by NHlaing** [comment]
20.08.2020

**Comment by mrmyothet** [comment]
> 20.08.2020

Congratulations!

**Comment by mrmyothet** [comment]
@NHlaing  
In order to distinguish with others.  
Please, create a folder `Programming Basics with Python--NDWH` and move your chapter by chapter folders into it.  
Then, create a `pull request` to merge your changes into `master` branch.

**Comment by mrmyothet** [comment]
when providing branch name,  
- avoid including special characters such as `(` etc
- avoid capital letters 
- can use dash `-` to differentiate words. eg.  `pbwp-ndwh`

![image](https://user-images.githubusercontent.com/16772482/90755016-acfd2d80-e300-11ea-9bba-0b280c869a74.png)

**Comment by mrmyothet** [comment]
Please, check the tasks box when you completed the tasks. 
- [ ] Create the folder `Programming Basics with Python--NDWH`. 
- [ ] Move chapter by chapter folders into `Programming Basics with Python--NDWH` folder.

**Comment by NHlaing** [comment]
@mrmyothet 
 I deleted "PBWP(ND)" and I make new branch "pbwp-book-nd" And then, I make pull request .
