### ISSUE TITLE
Code Your Own Quiz--KCL

### ISSUE THREAD

**Issue by mrmyothet** [mrmyothet/ipnd#15]
- use the Python programming language to build your own quiz.
- use a fill-in-the blank style to create a quiz that can even be used as a study tool to help you remember important vocabulary.

- [x] Lesson 01: Getting Set Up with Python
- [x] Lesson 02: Introduction to Serious Programming
- [x] Lesson 03: Work Session: Basic Debugging
- [x] Lesson 04: Variables & Strings
- [x] Lesson 05: Work Session: String Manipulation
- [x] Lesson 06: Input -> Function -> Output
- [x] Lesson 07: Work Session: Print vs Return
- [x] Lesson 08: Control Flow: If Statements & While Loops
- [x] Lesson 09: Deep Debugging
- [x] Lesson 10: Work Session: Mad Libs Generator
- [x] Lesson 11: Structured Data: Lists & For Loops
- [x] Lesson 12: How to Solve Problems
- [x] Lesson 13: Work Session: Mad Libs Continued
- [x] Lesson 14: Code Your Own Quiz

**Comment by Khun-Cho-Lwin** [comment]
I'v learned all of the Lesson.

**Comment by mrmyothet** [comment]
After you learned the lessons,  
create a pull request from the relevant branch. 
We will close the issue after merged the code from the pull request.
